version: 0.2

phases:
  build:
    commands:
      - echo "This is the build phase... Zipping my webpage bijender"
 
  post_build:
    commands:
      - echo "Deployed to S3"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
